const KEY='gold_services_v1';
const defaultData={
 clients:[
  {id:'CLI-001',name:'Productor Piloto Maule',type:'Productor',product:'Avellana Europea',ha:18,cert:'GLOBALG.A.P. IFA v6',status:'En diagnóstico'},
  {id:'CLI-002',name:'Productor Piloto Linares',type:'Productor',product:'Arándano',ha:12,cert:'GLOBALG.A.P. IFA v6',status:'Prospecto'}
 ],
 projects:[
  {id:'GS-2026-001',client:'Productor Piloto Maule',product:'Avellana Europea',stage:'Gap Analysis',progress:45,status:'En curso'},
  {id:'GS-2026-002',client:'Productor Piloto Linares',product:'Arándano',stage:'Diagnóstico',progress:20,status:'En curso'}
 ],
 lots:[
  {code:'GS-AV-2026-001',client:'Productor Piloto Maule',product:'Avellana Europea',variety:'Tonda di Giffoni',date:'2026-08-11',lab:'CEIMIC',result:'Conforme'},
  {code:'GS-AR-2026-001',client:'Productor Piloto Linares',product:'Arándano',variety:'—',date:'2026-08-11',lab:'CEIMIC',result:'Pendiente'}
 ],
 certifications:[], invoices:[]
};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||defaultData;
const services=[
 {line:'Gold Sampling',name:'Pack Básico (Muestreo + CEIMIC)',unit:'≤5 Ha',price:'6,5 UF',note:'Entrada — sampling + análisis de laboratorio.'},
 {line:'Gold Sampling',name:'Pack Full (Auditoría + Fiscalización + CEIMIC)',unit:'≤10 Ton packing',price:'8 UF',note:'Incluye fiscalización en línea de packing.'},
 {line:'Gold Sampling',name:'Asesoría Preventiva',unit:'Por visita',price:'3,5 UF',note:'Diagnóstico previo, sin certificación formal.'},
 {line:'Gold Sampling',name:'Mantención Mensual',unit:'Cliente/mes',price:'2,5 UF/mes',note:'Asesoría recurrente.'},
 {line:'Gold Certify',name:'Pack Esencial (GLOBALG.A.P. IFA v6)',unit:'≤15-20 Ha',price:'25 UF',note:'Gap analysis + plan + simulación + acompañamiento.'},
 {line:'Gold Certify',name:'Pack Integral Maule',unit:'Predio grande',price:'45 UF',note:'GLOBALG.A.P. + GRASP + SPRING, bodega y capacitación.'},
 {line:'Gold Sourcing',name:'Retainer Base',unit:'Comprador/mes',price:'US$1.200/mes',note:'Supervisión en terreno para comprador extranjero.'},
 {line:'Gold Sourcing',name:'Comisión por Volumen',unit:'Kg conforme',price:'US$0,05/kg',note:'Comisión por volumen despachado conforme.'}
];
const checklist=[
 'Registro del productor con número GGN ante organismo certificador acreditado',
 'Análisis de suelo y agua de riego con informe vigente',
 'Registro de aplicaciones fitosanitarias por cuartel',
 'Análisis de residuos de plaguicidas por lote según CAC/GL 33',
 'Plan de Manejo Integrado de Plagas documentado',
 'Capacitación del personal y registro de asistencia',
 'EPP, botiquín y procedimiento de emergencia',
 'Gestión de residuos y envases de agroquímicos',
 'Trazabilidad lote a lote, desde cuartel hasta contenedor',
 'Pre-auditoría interna Gold Services antes de auditoría oficial'
];
const markets=[
 ['Estados Unidos','Protocolo SAG–USDA/APHIS según zona de origen','Alta','Arándanos'],
 ['Unión Europea','LMR UE + trazabilidad lote a lote','Alta','Arándanos + Avellanas'],
 ['Reino Unido','Certificado fitosanitario + control fronterizo','Media-Alta','Arándanos + Avellanas'],
 ['China','Protocolo fitosanitario bilateral específico','Media','Arándanos + Avellanas'],
 ['Medio Oriente','Validar requisitos con organismo competente','Por evaluar','Arándanos + Avellanas']
];
function save(){localStorage.setItem(KEY,JSON.stringify(data));}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function badge(s){let c=s==='Conforme'||s==='En curso'?'green':s==='Prospecto'||s==='Pendiente'?'gold':'blue';return `<span class="badge ${c}">${esc(s)}</span>`}
function render(view='dashboard'){
 const titles={dashboard:'Dashboard',clientes:'Clientes',servicios:'Catálogo de servicios',proyectos:'Operaciones',trazabilidad:'Gold Trace — Trazabilidad',certificaciones:'Certificaciones',mercados:'Mercados objetivo'};
 document.getElementById('pageTitle').textContent=titles[view];
 document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 const c=document.getElementById('content');
 if(view==='dashboard') c.innerHTML=dashboard();
 if(view==='clientes') c.innerHTML=clientes();
 if(view==='servicios') c.innerHTML=servicios();
 if(view==='proyectos') c.innerHTML=proyectos();
 if(view==='trazabilidad') c.innerHTML=trazabilidad();
 if(view==='certificaciones') c.innerHTML=certificaciones();
 if(view==='mercados') c.innerHTML=mercadosView();
 bindView(view);
}
function dashboard(){const active=data.projects.filter(x=>x.status==='En curso').length;return `<div class="content-wrap"><div class="grid kpis"><div class="card"><div class="kpi-label">Clientes registrados</div><div class="kpi-value">${data.clients.length}</div><div class="kpi-note green">Productores + compradores</div></div><div class="card"><div class="kpi-label">Servicios en curso</div><div class="kpi-value">${active}</div><div class="kpi-note">Operaciones activas</div></div><div class="card"><div class="kpi-label">Lotes trazables</div><div class="kpi-value">${data.lots.length}</div><div class="kpi-note gold">Gold Trace</div></div><div class="card"><div class="kpi-label">Líneas comerciales</div><div class="kpi-value">3</div><div class="kpi-note">Sampling · Certify · Sourcing</div></div></div><div class="grid dashboard-grid" style="margin-top:16px"><div class="card"><div class="section-title"><h3>Operaciones recientes</h3><button class="btn ghost" data-action="go" data-view="proyectos">Ver todas</button></div><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Cliente</th><th>Producto</th><th>Etapa</th><th>Avance</th></tr></thead><tbody>${data.projects.map(p=>`<tr><td><strong>${esc(p.id)}</strong></td><td>${esc(p.client)}</td><td>${esc(p.product)}</td><td>${esc(p.stage)}</td><td><div class="progress"><span style="width:${p.progress}%"></span></div><span class="small">${p.progress}%</span></td></tr>`).join('')}</tbody></table></div></div><div class="card"><div class="section-title"><h3>Control de riesgo</h3></div><div class="checklist"><div class="check"><span>✓</span><div><strong>Regla 50/50</strong><br><span class="muted">Anticipo antes de terreno y saldo contra certificado interno.</span></div></div><div class="check"><span>✓</span><div><strong>Cero flujo de terceros</strong><br><span class="muted">Gold Services no toca el dinero de la fruta.</span></div></div><div class="check"><span>✓</span><div><strong>Certificación oficial</strong><br><span class="muted">La emite un organismo acreditado externo.</span></div></div><div class="check"><span>✓</span><div><strong>Productos foco</strong><br><span class="muted">Arándanos y avellanas.</span></div></div></div></div></div></div>`}
function clientes(){return `<div class="content-wrap"><div class="section-title"><h3>CRM de clientes y productores</h3><button class="btn primary" data-action="new-client">+ Nuevo cliente</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Cliente</th><th>Tipo</th><th>Producto</th><th>Hectáreas</th><th>Certificación</th><th>Estado</th></tr></thead><tbody>${data.clients.map(x=>`<tr><td>${esc(x.id)}</td><td><strong>${esc(x.name)}</strong></td><td>${esc(x.type)}</td><td>${esc(x.product)}</td><td>${esc(x.ha)}</td><td>${esc(x.cert)}</td><td>${badge(x.status)}</td></tr>`).join('')}</tbody></table></div></div></div>`}
function servicios(){return `<div class="content-wrap"><div class="grid service-grid">${services.map(s=>`<div class="card service-card"><span class="badge ${s.line==='Gold Certify'?'green':s.line==='Gold Sourcing'?'gold':'blue'}">${s.line}</span><h3>${s.name}</h3><div class="price">${s.price}</div><div class="muted">${s.unit}</div><p class="muted">${s.note}</p><button class="btn ghost" data-action="quote" data-service="${esc(s.name)}">Crear cotización</button></div>`).join('')}</div></div>`}
function proyectos(){return `<div class="content-wrap"><div class="section-title"><h3>Control operacional</h3><button class="btn primary" data-action="new-project">+ Nueva operación</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Cliente</th><th>Producto</th><th>Etapa</th><th>Avance</th><th>Estado</th></tr></thead><tbody>${data.projects.map(p=>`<tr><td><strong>${esc(p.id)}</strong></td><td>${esc(p.client)}</td><td>${esc(p.product)}</td><td>${esc(p.stage)}</td><td><div class="progress"><span style="width:${p.progress}%"></span></div><span class="small">${p.progress}%</span></td><td>${badge(p.status)}</td></tr>`).join('')}</tbody></table></div></div></div>`}
function trazabilidad(){return `<div class="content-wrap"><div class="grid trace-grid"><div class="card"><div class="section-title"><h3>Registrar / consultar lote</h3></div><form id="traceForm" class="form-grid"><div class="field full"><label>Código de lote</label><input name="code" placeholder="Ej. GS-AR-2026-002" required /></div><div class="field"><label>Producto</label><select name="product"><option>Arándano</option><option>Avellana Europea</option></select></div><div class="field"><label>Variedad</label><input name="variety" placeholder="Ej. Tonda di Giffoni" /></div><div class="field"><label>Cliente / productor</label><input name="client" required /></div><div class="field"><label>Laboratorio</label><input name="lab" value="CEIMIC" /></div><div class="field"><label>Resultado</label><select name="result"><option>Conforme</option><option>Pendiente</option><option>No conforme</option></select></div><div class="field full"><label>Fecha</label><input type="date" name="date" value="${new Date().toISOString().slice(0,10)}" /></div><div class="field full"><div class="form-actions"><button class="btn primary">Guardar lote y generar QR</button></div></div></form></div><div class="card"><div class="section-title"><h3>Último lote</h3></div><div id="qrBox" class="qr"><span class="muted">Selecciona un lote para visualizar su QR.</span></div></div></div><div class="card" style="margin-top:16px"><div class="section-title"><h3>Registro de trazabilidad</h3></div><div class="table-wrap"><table class="table"><thead><tr><th>Lote</th><th>Producto</th><th>Variedad</th><th>Productor</th><th>Fecha</th><th>Resultado</th><th></th></tr></thead><tbody>${data.lots.map(l=>`<tr><td class="trace-code">${esc(l.code)}</td><td>${esc(l.product)}</td><td>${esc(l.variety)}</td><td>${esc(l.client)}</td><td>${esc(l.date)}</td><td>${badge(l.result)}</td><td><button class="btn ghost" data-action="show-qr" data-code="${esc(l.code)}">QR</button></td></tr>`).join('')}</tbody></table></div></div></div>`}
function certificaciones(){return `<div class="content-wrap"><div class="card"><div class="section-title"><h3>Checklist GLOBALG.A.P. / SAG</h3><span class="badge blue">10 controles base</span></div><div class="checklist">${checklist.map((x,i)=>`<label class="check"><input type="checkbox" data-check="${i}"> <span>${i+1}. ${x}</span></label>`).join('')}</div><div style="margin-top:15px"><div class="muted">Avance del checklist</div><div class="progress" style="margin-top:6px"><span id="certProgress" style="width:0%"></span></div></div></div></div>`}
function mercadosView(){return `<div class="content-wrap"><div class="grid" style="grid-template-columns:repeat(2,1fr)">${markets.map(m=>`<div class="card market"><div><strong>${m[0]}</strong><div class="muted" style="margin-top:7px">${m[1]}</div><div class="small" style="margin-top:8px">Foco: ${m[3]}</div></div>${badge(m[2])}</div>`).join('')}</div><div class="card" style="margin-top:16px"><h3 style="color:var(--navy)">Criterio Gold Services</h3><p class="muted">La matriz se utiliza como guía comercial y de cumplimiento. Los aranceles, protocolos y requisitos específicos deben verificarse antes de comprometer una operación.</p></div></div>`}
function openModal(title,html,onSubmit){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=html;document.getElementById('modal').classList.remove('hidden');const f=document.querySelector('#modalBody form');if(f)f.onsubmit=e=>{e.preventDefault();onSubmit(new FormData(f));closeModal();render(document.querySelector('.nav-item.active')?.dataset.view||'dashboard');toast('Registro guardado correctamente');}}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function newClient(){openModal('Nuevo cliente',`<form class="form-grid"><div class="field full"><label>Nombre / razón social</label><input name="name" required></div><div class="field"><label>Tipo</label><select name="type"><option>Productor</option><option>Comprador internacional</option></select></div><div class="field"><label>Producto</label><select name="product"><option>Arándano</option><option>Avellana Europea</option></select></div><div class="field"><label>Hectáreas</label><input name="ha" type="number" min="0"></div><div class="field"><label>Certificación</label><input name="cert" value="GLOBALG.A.P. IFA v6"></div><div class="field full"><label>Estado</label><select name="status"><option>Prospecto</option><option>En diagnóstico</option><option>En curso</option></select></div><div class="field full"><div class="form-actions"><button class="btn primary">Guardar</button></div></div></form>`,fd=>{data.clients.push({id:'CLI-'+String(data.clients.length+1).padStart(3,'0'),name:fd.get('name'),type:fd.get('type'),product:fd.get('product'),ha:fd.get('ha')||0,cert:fd.get('cert'),status:fd.get('status')});save();})}
function newProject(){openModal('Nueva operación',`<form class="form-grid"><div class="field full"><label>Cliente</label><input name="client" required></div><div class="field"><label>Producto</label><select name="product"><option>Arándano</option><option>Avellana Europea</option></select></div><div class="field"><label>Etapa</label><select name="stage"><option>Diagnóstico</option><option>Gap Analysis</option><option>Plan de acción</option><option>Simulación</option><option>Muestreo</option><option>Mantención</option></select></div><div class="field"><label>Avance %</label><input name="progress" type="number" min="0" max="100" value="0"></div><div class="field"><label>Estado</label><select name="status"><option>En curso</option><option>Pendiente</option></select></div><div class="field full"><div class="form-actions"><button class="btn primary">Guardar</button></div></div></form>`,fd=>{data.projects.push({id:'GS-'+new Date().getFullYear()+'-'+String(data.projects.length+1).padStart(3,'0'),client:fd.get('client'),product:fd.get('product'),stage:fd.get('stage'),progress:Number(fd.get('progress')),status:fd.get('status')});save();})}
function bindView(view){document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>{const a=el.dataset.action;if(a==='go')render(el.dataset.view);if(a==='new-client')newClient();if(a==='new-project')newProject();if(a==='quote')toast('Cotización preparada para: '+el.dataset.service);if(a==='show-qr')showQr(el.dataset.code)});if(view==='trazabilidad'){document.getElementById('traceForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);const lot={code:fd.get('code'),product:fd.get('product'),variety:fd.get('variety')||'—',client:fd.get('client'),date:fd.get('date'),lab:fd.get('lab'),result:fd.get('result')};data.lots.unshift(lot);save();render('trazabilidad');showQr(lot.code);toast('Lote registrado y QR generado');};}if(view==='certificaciones'){document.querySelectorAll('[data-check]').forEach(x=>x.onchange=()=>{const n=[...document.querySelectorAll('[data-check]:checked')].length;document.getElementById('certProgress').style.width=(n/checklist.length*100)+'%';});}}
function showQr(code){const box=document.getElementById('qrBox');if(!box)return;box.innerHTML='';const canvas=document.createElement('canvas');box.appendChild(canvas);if(window.QRCode)QRCode.toCanvas(canvas,location.href.split('#')[0]+'?lot='+encodeURIComponent(code),{width:190,margin:2},()=>{});else box.innerHTML='<strong>'+esc(code)+'</strong>';}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2500)}
document.getElementById('nav').addEventListener('click',e=>{const b=e.target.closest('.nav-item');if(b)render(b.dataset.view)});document.getElementById('closeModal').onclick=closeModal;document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});document.getElementById('quickAdd').onclick=()=>newClient();document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gold-services-backup.json';a.click();URL.revokeObjectURL(a.href)};
render('dashboard');
